### ISSUE TITLE
Wont Work

### ISSUE THREAD

**Issue by masterdome** [AldousP/MyDearWatson#5]
When I put in the command sudo startelementary this is what it gives me sudo: startelementary: command not found. And when I do startelementary this pops up -su: startelementary: command not found. PLZ HELP :(

**Comment by GloverDonovan** [comment]
It worked for me. What Chromebook are you using and did you follow the instructions correctly? Do note that you'll need an Intel Processor.

**Comment by masterdome** [comment]
Never mind it just happened on that try! :) Thanks Anyway

**Comment by GloverDonovan** [comment]
Cool. Glad you got it to work!
